apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-locator
  namespace: php-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: office-locator
  template:
    metadata:
      labels:
        app: office-locator
    spec:
      containers:
        - name: office-locator
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: office-locator-db-secret
