name: Deploy to EKS

on:
  workflow_run:
    workflows:
      - Build & Push (Auto ECR)
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}

      NAMESPACE: ${{ vars.K8S_NAMESPACE }}
      DEPLOYMENT_NAME: ${{ vars.DEPLOYMENT_NAME }}
      CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply --validate=false -f k8s/namespace.yaml
          kubectl apply --validate=false -n $NAMESPACE -f k8s/secret.yaml
          kubectl apply --validate=false -n $NAMESPACE -f k8s/deployment.yaml
          kubectl apply --validate=false -n $NAMESPACE -f k8s/service.yaml

      - name: Update image
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME \
          $CONTAINER_NAME=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG \
          -n $NAMESPACE

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/$DEPLOYMENT_NAME \
          -n $NAMESPACE --timeout=300s

      - name: Show Service URL
        run: |
          kubectl get svc -n $NAMESPACE

      - name: Deployment completed
        run: echo "ðŸš€ Office Locator application deployed successfully on EKS"
