name: Destroy Complete Environment (RDS + EKS)

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # =========================
      # STEP 1 - DESTROY RDS
      # =========================
      - name: Terraform Init - RDS
        run: |
          cd terraform/RDS
          terraform init

      - name: Terraform Destroy - RDS
        run: |
          cd terraform/RDS
          terraform destroy -auto-approve

      # STEP 2 - DESTROY EKS
      - name: Terraform Init - EKS
        run: |
          cd terraform/EKS
          terraform init

      - name: Terraform Destroy - EKS
        run: |
          cd terraform/EKS
          terraform destroy -auto-approve
