name: Infrastructure Provisioning - EKS Cluster

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply - EKS
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # -------------------------
      # Checkout Source Code
      # -------------------------
      - name: Checkout code
        uses: actions/checkout@v5

      # -------------------------
      # Configure AWS (OIDC)
      # -------------------------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}
          role-duration-seconds: 1200

      # -------------------------
      # Install Terraform
      # -------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # -------------------------
      # Terraform - EKS
      # -------------------------
      - name: Terraform Init & Apply (EKS)
        working-directory: terraform/eks
        run: |
          terraform init -input=false
          terraform validate
          terraform apply -auto-approve -input=false

      # -------------------------
      # Export Terraform Outputs
      # -------------------------
      - name: Save Terraform Outputs
        run: |
          echo "CLUSTER_NAME=$(terraform -chdir=terraform/eks output -raw cluster_name)" >> $GITHUB_ENV
          echo "CLUSTER_ENDPOINT=$(terraform -chdir=terraform/eks output -raw cluster_endpoint)" >> $GITHUB_ENV
