name: Infrastructure Provisioning - RDS

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply - RDS
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # -------------------------
      # Checkout Source Code
      # -------------------------
      - name: Checkout code
        uses: actions/checkout@v5

      # -------------------------
      # Configure AWS (OIDC)
      # -------------------------
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}
          role-duration-seconds: 1200

      # -------------------------
      # Install Terraform
      # -------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # -------------------------
      # Terraform - RDS
      # -------------------------
      - name: Terraform Init & Apply (RDS)
        working-directory: terraform/rds
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
        run: |
          terraform init -input=false
          terraform validate
          terraform apply -auto-approve -input=false

      # -------------------------
      # Export Terraform Outputs
      # -------------------------
      - name: Save Terraform Outputs
        run: |
          echo "DB_ENDPOINT=$(terraform -chdir=terraform/rds output -raw rds_endpoint)" >> $GITHUB_ENV
          echo "DB_PORT=$(terraform -chdir=terraform/rds output -raw rds_port)" >> $GITHUB_ENV
          echo "DB_NAME=$(terraform -chdir=terraform/rds output -raw db_name)" >> $GITHUB_ENV
          echo "DB_USERNAME=$(terraform -chdir=terraform/rds output -raw db_username)" >> $GITHUB_ENV
